<?php
return [
'applicant'                 => ['type' => 's', 'title' => 'Заявитель'], 
'debtor'                    => ['type' => 's', 'title' => 'Должник'], 
'bankruptcy_trustee'        => ['type' => 's', 'title' => 'Конкурсный управляющий'],
'strategy'                  => ['type' => 'm', 'title' => 'Стратегия'], 
'state_duty'                => ['type' => 's', 'title' => 'Госпошлина'],
'deposit'                   => ['type' => 's', 'title' => 'Депозит'],
'number_case'               => ['type' => 's', 'title' => 'Номер дела'],
'link'                      => ['type' => 's', 'title' => 'Ссылка на дело в суде'],
'stage'                     => ['type' => 'm', 'title' => 'Стадия банкротства'],
'date_current_stage'        => ['type' => 'd', 'title' => 'Дата окончания текущей стадии'],
'information_creditors'     => ['type' => 's', 'title' => 'Информация о кредиторах'],
'property_valuation'        => ['type' => 's', 'title' => 'Информация об имуществе должника и его оценка'],
'bank_accounts'             => ['type' => 's', 'title' => 'Информация о банковских счетах должника'],
'information_invalidation'  => ['type' => 's', 'title' => 'Информация о признании сделок/платежей недействительными'],
'information_court'         => ['type' => 'm', 'title' => 'Информация об участии финансового управляющего на судебных заседаниях'],
'payments'                  => ['type' => 'm', 'title' => 'Платежи, сумма оплат, п/п'],
'subsidiary_liability'      => ['type' => 's', 'title' => 'Субсидиарная ответственность'],
'assessment_property'       => ['type' => 's', 'title' => 'Оценка имущества должностных лиц'],
'result_case'               => ['type' => 's', 'title' => 'Результат банкротства'],
];